# -*- coding: utf-8 -*-
"""streamlit_lung.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13-kCJSXuWOBxL2X-by0wm34YXJ2tc6Wc
"""

!pip install streamlit

import streamlit as st
from tensorflow.keras.models import load_model
import numpy as np
import cv2
from PIL import Image

# โหลดโมเดลที่บันทึกไว้
model = load_model('/content/lung_cancer_cnn_model.keras')

# ตั้งชื่อหมวดหมู่ที่โมเดลทำนายได้
categories = ['Benign', 'Malignant', 'Normal']

# ฟังก์ชันสำหรับการ preprocess ภาพ
def preprocess_image(image, img_size):
    image = np.array(image.convert('L'))  # แปลงเป็น grayscale
    image = cv2.resize(image, (img_size, img_size))  # ปรับขนาดภาพ
    image = image / 255.0  # Normalize ค่า
    image = np.expand_dims(image, axis=0)  # เพิ่มมิติ
    return image

# ฟังก์ชันสำหรับการทำนาย
def predict_image(image):
    img_size = 224  # ขนาดภาพที่โมเดลคาดหวัง
    processed_image = preprocess_image(image, img_size)
    prediction = model.predict(processed_image)
    predicted_class = np.argmax(prediction, axis=1)
    predicted_label = categories[predicted_class[0]]
    return predicted_label

st.title("Lung Cancer Detection App")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    # แสดงภาพที่อัปโหลด
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Image', use_column_width=True)

    # ทำการทำนาย
    st.write("Classifying...")
    label = predict_image(image)
    st.write(f"Prediction: {label}")

